### ISSUE TITLE
What has happened?

### ISSUE THREAD

**Issue by papel** [drivenotepad/app#22]
I am not able to use drivenotepad anymore. It's redirecting to another app whose page doesn't have info about it. The page says nothing about drivenotepad and doesn't have link to the source code.
Drivenotepad may have been hacked.

**Comment by d1manson** [comment]
Thanks for the concern, but in fact quite the opposite!

In the past week Drive Notepad was handed over to a new developer who plans to invest some time in revitalizing it and improving it.  The new developer has a very strong track record and I am very positive about the app's future.

In response to your message I have added some text in various places on github and the old drivenotepad website to make the situation clearer.
